// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// CoinStorage is an autogenerated mock type for the CoinStorage type
type CoinStorage struct {
	mock.Mock
}

// SendCoin provides a mock function with given fields: _a0, _a1, _a2
func (_m *CoinStorage) SendCoin(_a0 int, _a1 uuid.UUID, _a2 uuid.UUID) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for SendCoin")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCoinStorage creates a new instance of CoinStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCoinStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *CoinStorage {
	mock := &CoinStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
